bank/urls.py
from django.urls import path

from bank import views

app_name = 'bank'
urlpatterns = [
    path('',views.index,name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('detail/',views.detail,name='detail'),
    path('new/', views.new, name='new'),
    path('logout/', views.logout, name='logout'),
    path('card/',views.card,name='card'),
    path('add/', views.person_create_view, name='person_add'),
    path('<int:pk>/', views.person_update_view, name='person_change'),

    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),  # AJAX




]

bank_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('bank.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

bank/models.py
from django.db import models

class District(models.Model):
    name = models.CharField(max_length=100,unique=True)

    def __str__(self):
        return self.name



class Place(models.Model):
    name = models.CharField(max_length=100,unique=True)
    district = models.ForeignKey(District,on_delete=models.CASCADE)
    def __str__(self):
        return self.name



class Detail(models.Model):
    name = models.CharField(max_length=100,unique=True)
    dob = models.DateField(default=None)
    age = models.IntegerField()
    GENDER = (
        ('', ''),
        ('female', 'FEMALE'),
        ('male', 'MALE'),

    )
    gender = models.CharField(max_length=6, choices=GENDER, default='')
    phone = models.IntegerField()
    email = models.EmailField()
    address = models.TextField(max_length=500)
    district = models.ForeignKey(District,on_delete=models.CASCADE,null=True)
    place = models.ForeignKey(Place, on_delete=models.CASCADE,null=True)
    account_type = models.CharField(max_length=8)
    materials_required = models.CharField(max_length=20)

    def __str__(self):
        return self.name

bank/forms.py
from django import forms
from .models import Detail, Place


class DetailForm(forms.ModelForm):
    GENDER = (

        ('female', 'FEMALE'),
        ('male', 'MALE'),

    )
    gender = forms.ChoiceField(widget=forms.RadioSelect, choices=GENDER)

    account = (

        ('1','SAVINGS'),
        ('2', 'CURRENT')
    )
    account_type = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple,
                                             choices=account)
    materials = (
        ('1','CREDIT CARD'),
        ('2','DEBIT CARD'),
        ('3','CHEQUE BOOK')
    )
    materials_required = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple,
                                             choices=materials)
    YEARS = [x for x in range(1940, 2021)]
    dob = forms.DateField(widget=forms.SelectDateWidget(years=YEARS))
    class Meta:
        model = Detail
        fields=['name','dob','age','gender','phone','email','address','district','place','account_type','materials_required']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['place'].queryset = Place.objects.none()

        if 'district' in self.data:
            try:
                district_id = int(self.data.get('district'))
                self.fields['place'].queryset = Place.objects.filter(district_id=district_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['place'].queryset = self.instance.district.place_set.order_by('name')

bank/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, get_object_or_404

from . forms import DetailForm
from .models import Detail, Place


def index(request):
    return render(request,'index.html')

def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request,user)
            return render(request,'new.html')
        else:
            messages.info(request,"invalid bank")
            return render(request,'login.html')
    return render(request,'login.html')
def register (request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        cpassword = request.POST['cpassword']
        if password == cpassword:
            if User.objects.filter(username=username).exists():
                messages.info(request, "username already exists")
                return redirect('register')
            else:
                 user =User.objects.create_user(username=username,password=password)
                 user.save();
            return render(request,'login.html')

        else:
            messages.info(request,"incorrect password")
            return redirect('register')
    return render(request,'register.html')

def detail(request):
    form = DetailForm()
    if request.method == 'POST':
        name=request.POST.get('name',)
        age = request.POST.get('age', )
        dob = request.POST.get('dob', )
        gender = request.POST.get('gender', )
        address = request.POST.get('address', )
        phone = request.POST.get('phone', )
        email = request.POST.get('email', )
        district = request.POST.get('District', )
        place = request.POST.get('Place', )
        account_type = request.POST.get('account_type', )
        materials_required = request.POST.get('materials_required', )
        form = Detail(name=name,dob=dob,age=age,gender=gender,address=address,phone=phone,email=email,district=district,
                      place=place,account_type=account_type,materials_required=materials_required)
        form = DetailForm(request.POST or None, request.FILES, instance=form)
        if form.is_valid():
            form.save()
            return render(request, 'card.html')


    return render(request, 'detail.html', {'form': form})

def card(request):
    return render(request,'card.html')



def new(request):
    details = Detail.objects.all()
    return render(request,'new.html',{'details':details})

def logout(request):
    messages.info(request, "Logged out successfully!")
    return render(request,'index.html')

def person_create_view(request):
    form = DetailForm()
    if request.method == 'POST':
        form = DetailForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('person_add')
    return render(request, 'detail.html', {'form': form})


def person_update_view(request, pk):
    person = get_object_or_404(Detail, pk=pk)
    form = DetailForm(instance=detail)
    if request.method == 'POST':
        form = DetailForm(request.POST, instance=detail)
        if form.is_valid():
            form.save()
            return redirect('person_change', pk=pk)
    return render(request, 'detail.html', {'form': form})


# AJAX
def load_cities(request):
    district_id = request.GET.get('district_id')
    places = Place.objects.filter(district_id=district_id).all()
    return render(request, 'dropdown.html', {'places': places})

templates/card.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
     <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" >
    <link rel="stylesheet" href="{% static 'css/custom.css' %}" >
    <title>Title</title>
    <style>
        .card {
        margin: 0 auto; /* Added */
        float: none; /* Added */
        margin-bottom: 10px; /* Added */
   width: auto;
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%)

}
.card-body{
background-color:#C3E88D;
}
    </style>
</head>
<body>
<div class="card"  style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title" align="center"><b>QR BANK</b></h5><br>
      <br>
    <h6 class="card-subtitle mb-2 text-muted"  align="center">Application accepted</h6>
      <br>

   <button class="btn btn-dark"><a href="{% url 'credentials:index' %}" class="card-link">Go Back To Home</a></button>

</div>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</body>
</html>

templates/detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="https://kit.fontawesome.com/a076d05399.js" crossorigin="anonymous"></script>
    <style>
      html, body {
      display: flex;
      justify-content: center;
      font-family: Roboto, Arial, sans-serif;
      font-size: 15px;
      }
      form {
      border: 5px solid #000000;
      }
      input[type=text], input[type=password] {
      width: 100%;
      padding: 16px 8px;
      margin: 8px 0;
      display: inline-block;
      border: 1px solid #ccc;
      box-sizing: border-box;
      }
      button {
      background-color: #8ebf42;
      color: white;
      padding: 14px 0;
      margin: 10px 0;
      border: none;
      cursor: grabbing;
      width: 100%;
      }
      h1 {
      text-align:center;
      fone-size:18;
      }
      button:hover {
      opacity: 0.8;
      }
      .formcontainer {
      text-align: left;
      margin: 24px 50px 12px;
      }
      .container {
      padding: 16px 0;
      text-align:left;
      }
      span.psw {
      float: right;
      padding-top: 0;
      padding-right: 15px;
      }
      /* Change styles for span on extra small screens */
      @media screen and (max-width: 300px) {
      span.psw {
      display: block;
      float: none;
      }
    </style>

</head>
<body style=" background-image: url({% static 'img/bg.jpg' %});">
<div align="center">
<h1 style="text-align:center; color:black;">DETAIL PAGE</h1><br>
<div class="container py-5" align="center">
 <form  method="POST" align="center" action="" id="personForm" data-cities-url="{% url 'credentials:ajax_load_cities' %}">
    {% csrf_token %}
     {{form.as_p}}


     <div class="container">
       <button type="submit" class="btn" onclick="openPopup()">Submit</button>
      </div>


         <br>
         <div class="button">
             <button> <a href="/logout">logout</a> </button>
      </div>

   </form>
        </div>
</div>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_district").change(function () {
        const url = $("#personForm").attr("data-cities-url");  // get the url of the `load_cities` view
        const districtId = $(this).val();  // get the selected country ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
            data: {
                'district_id': districtId       // add the country id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                $("#id_place").html(data);


                let html_data = '<option value="">---------</option>';
                data.forEach(function (place) {
                    html_data += `<option value="${place.id}">${place.name}</option>`
                });
                console.log(html_data);
                $("#id_place").html(html_data);
                  }
        });

    });


</script>



</body>
</html>

templates/dropdown.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<option value="">---------</option>
{% for place in places %}
<option value="{{ place.pk }}">{{ place.name }}</option>
{% endfor %}
</body>
</html>

templates/header.html
{% load static %}
    <header>
  <center>
    <img src="{% static 'img/logo.png' %}" alt="logo image" width="100px;" height="100px";>
  </center>
</header>

templates/index.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
     <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" >
    <link rel="stylesheet" href="{% static 'css/custom.css' %}" >
<title>QR Bank</title>

</head>
<body>
{% include 'header.html' %}
{% include 'navbar.html' %}
<BR>
<pre>

    <h2 style="text-align:center; color: #927623;
font-family: arial, sans-serif;
font-size: 30px;
font-weight: bold;
margin-top: 0px;
margin-bottom: 1px;" >WELCOME TO QR BANK</h2>
<img src="{% static 'img/banner.png' %}" alt="logo image" width="1500px;" height="500px;">

    </pre>
<div class="container-fluid">

       <P style="
  text-indent: 50px;
  text-transform: uppercase;
text-align:left"
><b>

            Lorem Ipsum is simply dummy text of the printing and typesetting industry.
            Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
            when an unknown printer took a galley of type and scrambled it to make a type specimen book.
            It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.
            It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages,
            and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.

</b></P>

</div>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

templates/login.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>Login Page</title>
    <style>
      html, body {
      display: flex;
      justify-content: center;
      font-family: Roboto, Arial, sans-serif;
      font-size: 15px;
      }
      form {
      border: 5px solid #f1f1f1;
      }
      input[type=text], input[type=password] {
      width: 100%;
      padding: 16px 8px;
      margin: 8px 0;
      display: inline-block;
      border: 1px solid #ccc;
      box-sizing: border-box;
      }
      button {
      background-color: #8ebf42;
      color: white;
      padding: 14px 0;
      margin: 10px 0;
      border: none;
      cursor: grabbing;
      width: 100%;
      }
      h1 {
      text-align:center;
      fone-size:18;
      }
      button:hover {
      opacity: 0.8;
      }
      .formcontainer {
      text-align: left;
      margin: 24px 50px 12px;
      }
      .container {
      padding: 16px 0;
      text-align:left;
      }
      span.psw {
      float: right;
      padding-top: 0;
      padding-right: 15px;
      }
      /* Change styles for span on extra small screens */
      @media screen and (max-width: 300px) {
      span.psw {
      display: block;
      float: none;
      }

  body {
  background-image: url({% static 'img/bgg.png' %});
  background-repeat: no-repeat;
  background-attachment: fixed;
  background-size: cover;
}
.button {
  background-color: white;
  color: black;
  border: 2px solid #4CAF50; /* Green */
}
    </style>
</head>
<body style=" background-image: url({% static 'img/bg1.png' %});">
<div class="container py-5" align="center">
  <h1 style="color:white;">Login</h1>
  <br>
  <BR>
  <form method="POST" align="center" action="">
    {% csrf_token %}

    <div>
    <label style="color:white;"><pre><b>USERNAME</b></pre></label><input  type="text" name="username"><br>
    <label style="color:white;"><pre><b>PASSWORD</b></pre></label><input type="password" name="password"><br>
    <pre><input type="submit"></pre><br>
    </div>
  </form>
  <p style="color:white;" class="text-center">Don't have an account? <button ><a  href="/register">Create an account</a></button></p>
</div>

</body>
</html>

templates/logout.html
<form method='POST'>
    {% csrf_token %}
    Are you sure you want to logout?
    <input type="submit">
</form>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-warning">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
       <li class="nav-item active">
        <a class="nav-link" href="{% url 'credentials:index' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'credentials:register' %}">Register</a>
      </li>
      <li class="nav-item ">
        <a class="nav-link" href="{% url 'credentials:login' %}">Login</a>
      </li>
      <li class="nav-item dropdown  {% if 'credentials' in request.path %} active {% endif %}">
        <a class="nav-link dropdown-toggle" href=""  id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
Branches
        </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Thrissur">Thrissur</a>
              <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kollam">Kollam</a>
              <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Palakkad">Palakkad</a>
              <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kannur">Kannur</a>
               <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Ernankulam">Ernankulam</a>
          </div>
      </li>

    </ul>
  </div>
</nav>

templates/new.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <title>Title</title>
    <style>
body {
  background-image: url({% static 'img/bgg.png' %});
  background-repeat: no-repeat;
  background-attachment: fixed;
  background-size: cover;
}
</style>
</head>
<body>


<p style="color:white;">Enter you details <button><a href="{% url 'credentials:detail' %}">Here</a></button></p>
</body>
</html>

templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register Here</title>
<style>
      html, body {
      display: flex;
      justify-content: center;
      font-family: Roboto, Arial, sans-serif;
      font-size: 15px;
      }
      form {
      border: 5px solid #f1f1f1;
      }
      input[type=text], input[type=password] {
      width: 100%;
      padding: 16px 8px;
      margin: 8px 0;
      display: inline-block;
      border: 1px solid #ccc;
      box-sizing: border-box;
      }
      button {
      background-color: #8ebf42;
      color: white;
      padding: 14px 0;
      margin: 10px 0;
      border: none;
      cursor: grabbing;
      width: 100%;
      }
      h1 {
      text-align:center;
      fone-size:18;
      }
      button:hover {
      opacity: 0.8;
      }
      .formcontainer {
      text-align: left;
      margin: 24px 50px 12px;
      }
      .container {
      padding: 16px 0;
      text-align:left;
      }
      span.psw {
      float: right;
      padding-top: 0;
      padding-right: 15px;
      }
      /* Change styles for span on extra small screens */
      @media screen and (max-width: 300px) {
      span.psw {
      display: block;
      float: none;
      }
    </style>

</head>

<body style=" background-image: url({% static 'img/bg1.png' %});">
<div align="center">
<h1 style="text-align:center; color:white;">REGISTRATION FORM</h1><br>
<form action="" method="POST" align="center" enctype="multipart/form-data">
   {% csrf_token %}
   {{form.as_p}}

   		<div>
      <div class="form-group">
   <label style="color:white;"><b><pre>USERNAME</pre></b></label><input type="text" class="form-control"  name="USERNAME" ><br></div>
   <div class="form-group"><label style="color:white;"><b><pre>PASSWORD</pre></b></label><input type="password" class="form-control"  name="PASSWORD" ><br></div>
    <div class="form-group"><label style="color:white;"><b><pre>CONFIRM PASSWORD</pre></b></label><input type="password" class="form-control"  name="CONFIRM PASSWORD"><br></div>
 <input type="submit">
   </div>

	</form>
	<p style="color:white;" class="text-center">If you already have an account,<button> <a href="/login">login here</a> </button></p>
  </div>
{% for msg in messages %}
<h1>{{msg }}</h1>
{% endfor %}
</body>
</html>